// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICVBSUcg8gyKZ-OxRgt7Ua9Vk8iA67js',
    appId: '1:885554585377:web:4f0334a7d502952bcca860',
    messagingSenderId: '885554585377',
    projectId: 'olci-dart',
    authDomain: 'olci-dart.firebaseapp.com',
    databaseURL: 'https://olci-dart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'olci-dart.appspot.com',
    measurementId: 'G-EHCE61LZXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP6AGZgMq-QM7oug4p6b9tvyGwjKIufgA',
    appId: '1:885554585377:android:a6ce29c9a09b45afcca860',
    messagingSenderId: '885554585377',
    projectId: 'olci-dart',
    databaseURL: 'https://olci-dart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'olci-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAP7IuoIxQ_kA8tCI9B6PYbVKWuTxV6hg',
    appId: '1:885554585377:ios:ac94cb5096b6772fcca860',
    messagingSenderId: '885554585377',
    projectId: 'olci-dart',
    databaseURL: 'https://olci-dart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'olci-dart.appspot.com',
    iosClientId: '885554585377-mrt21gvhs1s0a4uovrv2ho34duj5c3ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAP7IuoIxQ_kA8tCI9B6PYbVKWuTxV6hg',
    appId: '1:885554585377:ios:ac94cb5096b6772fcca860',
    messagingSenderId: '885554585377',
    projectId: 'olci-dart',
    databaseURL: 'https://olci-dart-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'olci-dart.appspot.com',
    iosClientId: '885554585377-mrt21gvhs1s0a4uovrv2ho34duj5c3ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
